# Generated by Django 4.1 on 2022-09-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMercado', '0002_muebles_vehiculos'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrodomesticos',
            name='marca',
            field=models.CharField(default='hola', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muebles',
            name='material',
            field=models.CharField(default='hola', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='marca',
            field=models.CharField(default='hola', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electrodomesticos',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='muebles',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
